GET https://github.com/SoumyaSubhrajit

###

# POST http://localhost:3000/register
# Content-Type: application/json

# {
#   "username": "abhijit",
#   "password": "abhio456",
#   "email": "abhi1234@gmail.com"
# }

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "Soumya Subhrajit Bag",
  "password": "kanha456"
}