GET https://github.com/SoumyaSubhrajit

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "Flora rimjhim Bag",
  "password": "flora456",
  "email": "flora123@gmail.com"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "Soumya Subhrajit Bag",
  "password": "kanha456"
}